export const tours = [
  {
    id: 1,
    slug: "isla-saona",
    title: "Isla Saona",
    category: "Isla",
    duration: "8 horas",
    price: 89,
    maxPrice: 149,
    rating: 4.9,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80",
    description: "Navega hasta la paradisíaca Isla Saona, con piscina natural y playa virgen.",
    destino: "Punta Cana",
    badge: "Más popular",
  },
  {
    id: 2,
    slug: "nado-con-delfines",
    title: "Nado con Delfines",
    category: "Aventura",
    duration: "3 horas",
    price: 100,
    maxPrice: 179,
    rating: 5.0,
    reviews: 198,
    image: "https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=800&q=80",
    description: "Una experiencia única nadando junto a delfines en aguas cristalinas.",
    destino: "Punta Cana",
    badge: "Recomendado",
  },
  {
    id: 3,
    slug: "catamaran-sunset",
    title: "Catamarán Sunset",
    category: "Náutico",
    duration: "4 horas",
    price: 120,
    maxPrice: 200,
    rating: 4.8,
    reviews: 145,
    image: "https://plus.unsplash.com/premium_photo-1680831748352-3a6f45a3468e?w=800&q=80",
    description: "Navega al atardecer con open bar, snorkel y música en vivo.",
    destino: "Punta Cana",
    badge: null,
  },
  {
    id: 4,
    slug: "aventura-buggy",
    title: "Aventura en Buggy",
    category: "Aventura",
    duration: "5 horas",
    price: 89,
    maxPrice: 149,
    rating: 4.7,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1650170842663-fb0231c79d00?w=800&q=80",
    description: "Recorre la selva y playas escondidas en buggy todoterreno.",
    destino: "Santo Domingo",
    badge: null,
  },
  {
    id: 5,
    slug: "ciudad-colonial",
    title: "Ciudad Colonial",
    category: "Cultural",
    duration: "6 horas",
    price: 65,
    maxPrice: 95,
    rating: 4.6,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1598918429966-1ac4f6143bc2?w=800&q=80",
    description: "Explora la primera ciudad del Nuevo Mundo, Patrimonio de la UNESCO.",
    destino: "Santo Domingo",
    badge: null,
  },
  {
    id: 6,
    slug: "whale-watching",
    title: "Avistamiento de Ballenas",
    category: "Naturaleza",
    duration: "7 horas",
    price: 110,
    maxPrice: 160,
    rating: 4.9,
    reviews: 76,
    image: "https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=800&q=80",
    description: "Observa ballenas jorobadas en su hábitat natural en Samaná.",
    destino: "Samaná",
    badge: "Temporada",
  },
];

export const destinos = [
  {
    id: 1,
    name: "Punta Cana",
    country: "República Dominicana",
    image: "https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800&q=80",
    tours: 12,
    lat: 18.5601,
    lng: -68.3725,
    description: "Playas de arena blanca y aguas turquesas. El paraíso del Caribe.",
  },
  {
    id: 2,
    name: "Santo Domingo",
    country: "República Dominicana",
    image: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800&q=80",
    tours: 8,
    lat: 18.4861,
    lng: -69.9312,
    description: "La primera ciudad del Nuevo Mundo. Historia, cultura y gastronomía.",
  },
  {
    id: 3,
    name: "Samaná",
    country: "República Dominicana",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
    tours: 6,
    lat: 19.2061,
    lng: -69.3363,
    description: "Cascadas, ballenas jorobadas y naturaleza virgen.",
  },
];

export const testimonios = [
  {
    name: "María García",
    country: "España",
    avatar: "https://i.pravatar.cc/80?img=5",
    rating: 5,
    text: "El tour a Isla Saona fue absolutamente mágico. La piscina natural es increíble y los guías son muy profesionales.",
    tour: "Isla Saona",
  },
  {
    name: "Carlos Rodríguez",
    country: "México",
    avatar: "https://i.pravatar.cc/80?img=12",
    rating: 5,
    text: "Nadar con delfines fue la experiencia de mi vida. Mis hijos no paran de hablar de ello. ¡100% recomendado!",
    tour: "Nado con Delfines",
  },
  {
    name: "Ana Martínez",
    country: "Colombia",
    avatar: "https://i.pravatar.cc/80?img=9",
    rating: 5,
    text: "El catamarán al atardecer con open bar fue perfecto para nuestra luna de miel. Gracias Fantasy Travels.",
    tour: "Catamarán Sunset",
  },
];

export const blogPosts = [
  {
    id: 1,
    slug: "que-hacer-punta-cana-2026",
    title: "Qué hacer en Punta Cana en 2026: Guía completa",
    excerpt: "Descubre las mejores actividades, playas y experiencias que no te puedes perder en Punta Cana este año.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    date: "2026-03-15",
    readTime: "8 min",
    category: "Guías",
  },
  {
    id: 2,
    slug: "isla-saona-guia-completa",
    title: "Isla Saona: Todo lo que necesitas saber antes de ir",
    excerpt: "La isla más famosa de República Dominicana. Cómo llegar, qué llevar y los mejores consejos para disfrutarla.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    date: "2026-02-28",
    readTime: "6 min",
    category: "Destinos",
  },
  {
    id: 3,
    slug: "mejor-epoca-visitar-caribe",
    title: "Mejor época para visitar el Caribe en 2026",
    excerpt: "Temporadas, clima, precios y consejos para planificar tu viaje perfecto al Caribe.",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
    date: "2026-02-10",
    readTime: "5 min",
    category: "Consejos",
  },
];
