export const tours = [
  {
    id: 1,
    slug: "private-catamaran-saona",
    title: "Private Catamaran to Saona Island",
    category: "Island",
    duration: "8 hours",
    price: 179.99,
    maxPrice: 179.99,
    rating: 5.0,
    reviews: 312,
    image: "https://everythingpuntacana.com/wp-content/gallery/la-romana-charters-adventure-82/private-catamaran-punta-cana-01.jpg",
    description: "All-inclusive getaway to Saona Island with snorkeling and natural pool. Departures: 8:00 AM or 8:30 AM.",
    destino: "Punta Cana",
    badge: "Most Popular",
    startTimes: "8:00 AM / 8:30 AM",
  },
  {
    id: 2,
    slug: "catamaran-coast",
    title: "Private Catamaran Along the Coast",
    category: "Nautical",
    duration: "8 hours",
    price: 149.99,
    maxPrice: 149.99,
    rating: 4.9,
    reviews: 198,
    image: "https://maltaislandtours.com/wp-content/uploads/2022/02/malta-catamaran-cruise-sunset-1492x1000.jpg",
    description: "Punta Cana coast, open bar, snorkeling and music. Departures: 8:00 AM or 12:00 PM.",
    destino: "Punta Cana",
    badge: "Recommended",
    startTimes: "8:00 AM / 12:00 PM",
  },
  {
    id: 3,
    slug: "horseback-riding",
    title: "Horseback Riding",
    category: "Adventure",
    duration: "2.5 hours",
    price: 79.99,
    maxPrice: 79.99,
    rating: 4.8,
    reviews: 145,
    image: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,h_962,q_65,w_640/v1/clients/whitemountainsnh/ThingsToDo_HorsebackRiding_116c3aa9-1131-4f96-a3dd-64742a4e59bc.jpg",
    description: "Guided horseback ride through the landscapes of Punta Cana. Departures: 9:00 AM, 11:00 AM, 12:30 PM.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "9:00 AM / 11:00 AM / 12:30 PM",
  },
  {
    id: 4,
    slug: "monkey-land",
    title: "Monkey Land Tour",
    category: "Nature",
    duration: "2.5 hours",
    price: 99.99,
    maxPrice: 99.99,
    rating: 4.9,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=800&q=80",
    description: "Interact with monkeys in a tropical setting. Departures: 7:00 AM or 1:00 PM.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "7:00 AM / 1:00 PM",
  },
  {
    id: 5,
    slug: "speed-boat",
    title: "Speed Boat Tour",
    category: "Nautical",
    duration: "2.5 hours",
    price: 84.99,
    maxPrice: 84.99,
    rating: 4.7,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80",
    description: "Pure adrenaline on the water. Departures: 8:00 AM, 11:00 AM, 1:00 PM.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "8:00 AM / 11:00 AM / 1:00 PM",
  },
  {
    id: 6,
    slug: "whale-watching-samana",
    title: "Whale Watching in Samaná",
    category: "Nature",
    duration: "8 hours",
    price: 199.99,
    maxPrice: 199.99,
    rating: 5.0,
    reviews: 76,
    image: "https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=800&q=80",
    description: "Close encounter with humpback whales in Samaná. Departure: 7:15 AM.",
    destino: "Samaná",
    badge: "Seasonal",
    startTimes: "7:15 AM",
  },
  {
    id: 7,
    slug: "party-boat",
    title: "Party Boat Punta Cana",
    category: "Nautical",
    duration: "3 hours",
    price: 74.99,
    maxPrice: 74.99,
    rating: 4.8,
    reviews: 167,
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0f/39/78/39.jpg",
    description: "All-inclusive with open bar and music. Departures: 11:30 AM or 2:30 PM.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "11:30 AM / 2:30 PM",
  },
  {
    id: 8,
    slug: "swimming-dolphins",
    title: "Swimming with Dolphins",
    category: "Adventure",
    duration: "2.5 hours",
    price: 124.99,
    maxPrice: 124.99,
    rating: 5.0,
    reviews: 298,
    image: "https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=800&q=80",
    description: "Unique experience swimming with dolphins in Cabeza de Toro.",
    destino: "Punta Cana",
    badge: "Recommended",
    startTimes: "8:30 AM / 9:30 AM / 11:30 AM / 12:00 PM",
  },
  {
    id: 10,
    slug: "atv-buggy",
    title: "ATV / Buggy Adventure",
    category: "Adventure",
    duration: "3 hours",
    price: 84.99,
    maxPrice: 84.99,
    rating: 4.7,
    reviews: 134,
    image: "https://cdn2.veltra.com/ptr/20230221233952_1503055499_1230_0.jpg?imwidth=550&impolicy=custom",
    description: "Off-road thrills through Punta Cana. Departures: 7:00 AM or 1:00 PM.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "7:00 AM / 1:00 PM",
  },
  {
    id: 11,
    slug: "roundtrip-shuttle",
    title: "Round-Trip Shuttle",
    category: "Transportation",
    duration: "Flexible",
    price: 149.99,
    maxPrice: 149.99,
    rating: 4.6,
    reviews: 88,
    image: "https://www.ridebooker.com/images/vehicles/whistler-shuttle.webp",
    description: "Airport/hotel transfers. Minimum 4 people. Flexible schedule.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "Flexible",
  },
  {
    id: 12,
    slug: "saona-speedboat",
    title: "Private Speedboat to Saona Island",
    category: "Island",
    duration: "8 hours",
    price: 189.99,
    maxPrice: 189.99,
    rating: 5.0,
    reviews: 221,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    description: "Exclusive private speedboat to Saona Island with natural pool stop.",
    destino: "Punta Cana",
    badge: "Exclusive",
    startTimes: "8:00 AM / 8:30 AM",
  },
  {
    id: 13,
    slug: "buggy-offroad-mud-beach",
    title: "Buggy Off-Road – Mud & Beach",
    category: "Adventure",
    duration: "4 hours",
    price: 59,
    maxPrice: 59,
    rating: 4.8,
    reviews: 187,
    image: "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&q=80",
    description: "Off-road buggy adventure through mud and beaches of Punta Cana.",
    destino: "Punta Cana",
    badge: "Best Seller",
    startTimes: "8:00 AM / 1:00 PM",
  },
  {
    id: 14,
    slug: "atv-water-cave-macao",
    title: "ATV Water Cave & Macao Beach",
    category: "Adventure",
    duration: "3.5 hours",
    price: 59,
    maxPrice: 59,
    rating: 4.9,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&q=80",
    description: "Explore water caves and the famous Macao Beach by ATV.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "8:00 AM / 1:00 PM",
  },
  {
    id: 15,
    slug: "catamaran-party-snorkel",
    title: "Catamaran Party & Snorkel",
    category: "Nautical",
    duration: "3.5 hours",
    price: 59,
    maxPrice: 59,
    rating: 4.7,
    reviews: 203,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzpVzP67gT63_6u9LeIHBnk4zYSUERzQmdmA&s",
    description: "Catamaran party with snorkeling and open bar.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "9:00 AM / 1:00 PM",
  },
  {
    id: 17,
    slug: "snorkeling-cruise-open-bar",
    title: "Snorkeling Cruise with Open Bar",
    category: "Nautical",
    duration: "3.5 hours",
    price: 89,
    maxPrice: 89,
    rating: 4.9,
    reviews: 178,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    description: "Small group snorkeling with open bar and snacks.",
    destino: "Punta Cana",
    badge: "Best Seller",
    startTimes: "9:00 AM / 1:00 PM",
  },
  {
    id: 18,
    slug: "saona-island-tour",
    title: "Saona Island Tour",
    category: "Island",
    duration: "12 hours",
    price: 89,
    maxPrice: 89,
    rating: 4.9,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    description: "Full day at Saona Island with lunch, drinks and natural pool.",
    destino: "Punta Cana",
    badge: "Special Offer",
    startTimes: "7:00 AM",
  },
  {
    id: 19,
    slug: "jungle-buggies",
    title: "Jungle Buggies",
    category: "Adventure",
    duration: "5 hours",
    price: 89,
    maxPrice: 89,
    rating: 4.7,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&q=80",
    description: "Buggy adventure through the tropical jungle of Punta Cana.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "8:00 AM / 1:00 PM",
  },
  {
    id: 20,
    slug: "higuey-city-luxury-tour",
    title: "Private Higüey Tour – Culture & History",
    category: "Cultural",
    duration: "5 hours",
    price: 90,
    maxPrice: 90,
    rating: 4.8,
    reviews: 67,
    image: "https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=auto,quality=60,height=450,dpr=1/tour_img/8398d6d6d7d396a8580ba1595b56ddc3812bde9abadd2e913ae1061321b03fe6.jpeg",
    description: "Luxury private tour of Higüey: culture, history and local shopping.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "9:00 AM",
  },
  {
    id: 21,
    slug: "coco-bongo-regular",
    title: "Coco Bongo – Regular Open Bar",
    category: "Entertainment",
    duration: "4.5 hours",
    price: 90,
    maxPrice: 90,
    rating: 4.8,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    description: "Spectacular show with open bar at Coco Bongo Punta Cana.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "10:30 PM",
  },
  {
    id: 22,
    slug: "santo-domingo-city-tour",
    title: "Santo Domingo City Tour",
    category: "Cultural",
    duration: "12 hours",
    price: 95,
    maxPrice: 95,
    rating: 4.7,
    reviews: 112,
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/97/b0/34/caption.jpg?w=1200&h=-1&s=1",
    description: "Explore the Colonial Zone, the Malecón and historic monuments.",
    destino: "Santo Domingo",
    badge: null,
    startTimes: "7:00 AM",
  },
  {
    id: 23,
    slug: "ziplines-punta-cana",
    title: "Ziplines Punta Cana",
    category: "Adventure",
    duration: "4 hours",
    price: 95,
    maxPrice: 95,
    rating: 4.8,
    reviews: 89,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP_MPQs6DQgiXLObfLwjFxUo6SPbIUiF-lwg&s",
    description: "Fly over the jungle on high-speed ziplines.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "8:00 AM / 1:00 PM",
  },
  {
    id: 24,
    slug: "cultural-safari-sightseeing",
    title: "Cultural Safari & Sightseeing",
    category: "Cultural",
    duration: "10 hours",
    price: 95,
    maxPrice: 95,
    rating: 4.7,
    reviews: 76,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    description: "Discover Dominican culture: countryside, plantations and local life.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "7:30 AM",
  },
  {
    id: 26,
    slug: "catalina-island-snorkel",
    title: "Catalina Island Tour + Snorkel",
    category: "Island",
    duration: "10 hours",
    price: 125,
    maxPrice: 125,
    rating: 4.9,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    description: "Catalina Island with coral reef snorkeling and lunch included.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "7:00 AM",
  },
  {
    id: 27,
    slug: "domitai-park-adventure",
    title: "Domitai Park – Buggy, Zipline, Horseback & Cenote",
    category: "Adventure",
    duration: "9 hours",
    price: 129,
    maxPrice: 129,
    rating: 4.9,
    reviews: 134,
    image: "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&q=80",
    description: "Complete adventure park: buggy, zipline, horseback riding and cenote.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "8:00 AM",
  },
  {
    id: 28,
    slug: "aqua-adventure-buggies-kart",
    title: "Aqua Adventure: Buggies & Aqua Kart",
    category: "Adventure",
    duration: "4 hours",
    price: 129,
    maxPrice: 129,
    rating: 4.8,
    reviews: 87,
    image: "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80",
    description: "Combination of off-road buggies and aqua karts.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "8:00 AM / 1:00 PM",
  },
  {
    id: 29,
    slug: "aqua-adventure-buggies-jetski",
    title: "Aqua Adventure: Buggies + Jet Ski",
    category: "Adventure",
    duration: "4 hours",
    price: 129,
    maxPrice: 129,
    rating: 4.7,
    reviews: 72,
    image: "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80",
    description: "Double adventure: off-road buggies and jet ski on the sea.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "8:00 AM / 1:00 PM",
  },
  {
    id: 30,
    slug: "scape-park-tour",
    title: "Scape Park Tour",
    category: "Adventure",
    duration: "10 hours",
    price: 129,
    maxPrice: 129,
    rating: 4.9,
    reviews: 267,
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    description: "Eco park with cenotes, ziplines, caves and beach.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "8:00 AM",
  },
  {
    id: 31,
    slug: "deep-sea-fishing",
    title: "Deep Sea Fishing",
    category: "Nautical",
    duration: "4 hours",
    price: 129,
    maxPrice: 129,
    rating: 4.8,
    reviews: 94,
    image: "https://images.unsplash.com/photo-1545816250-e12bedba42ba?w=800&q=80",
    description: "Sport fishing in the deep waters of Punta Cana.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "7:00 AM / 12:00 PM",
  },
  {
    id: 32,
    slug: "coco-bongo-gold",
    title: "Coco Bongo – Gold Member Open Bar",
    category: "Entertainment",
    duration: "4.5 hours",
    price: 175,
    maxPrice: 175,
    rating: 5.0,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    description: "VIP Gold experience at Coco Bongo with premium open bar.",
    destino: "Punta Cana",
    badge: "Best Seller",
    startTimes: "10:30 PM",
  },
  {
    id: 33,
    slug: "santo-domingo-semi-private",
    title: "Santo Domingo Semi-Private (6 people)",
    category: "Cultural",
    duration: "10 hours",
    price: 195,
    maxPrice: 195,
    rating: 4.8,
    reviews: 45,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    description: "Semi-private tour of Santo Domingo, max 6 people.",
    destino: "Santo Domingo",
    badge: null,
    startTimes: "7:00 AM",
  },
  {
    id: 34,
    slug: "double-dolphins",
    title: "Swimming with 2 Dolphins",
    category: "Adventure",
    duration: "4 hours",
    price: 199,
    maxPrice: 199,
    rating: 5.0,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=800&q=80",
    description: "Double experience: swim with 2 dolphins at once.",
    destino: "Punta Cana",
    badge: "Top Pick",
    startTimes: "9:00 AM / 11:00 AM",
  },
  {
    id: 35,
    slug: "coco-bongo-gold-suv",
    title: "Coco Bongo Gold + Luxury SUV Transfer",
    category: "Entertainment",
    duration: "5 hours",
    price: 225,
    maxPrice: 225,
    rating: 5.0,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    description: "Coco Bongo Gold Member with luxury SUV transportation.",
    destino: "Punta Cana",
    badge: "Exclusive",
    startTimes: "9:30 PM",
  },
  {
    id: 36,
    slug: "santo-domingo-deluxe-private",
    title: "Santo Domingo Deluxe Private",
    category: "Cultural",
    duration: "10 hours",
    price: 695,
    maxPrice: 695,
    rating: 5.0,
    reviews: 34,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    description: "Luxury private tour of Santo Domingo in a small group.",
    destino: "Santo Domingo",
    badge: "Best Seller",
    startTimes: "7:00 AM",
  },
  {
    id: 37,
    slug: "private-catamaran-snorkel-party",
    title: "Private Catamaran – Snorkel, Natural Pool & Party",
    category: "Nautical",
    duration: "4.5 hours",
    price: 950,
    maxPrice: 950,
    rating: 5.0,
    reviews: 28,
    image: "https://images.unsplash.com/photo-1500514966906-fe245eea9344?w=800&q=80",
    description: "Exclusive private catamaran with snorkeling, natural pool and party.",
    destino: "Punta Cana",
    badge: null,
    startTimes: "9:00 AM / 1:00 PM",
  },
];

export const destinos = [
  {
    id: 1,
    name: "Punta Cana",
    country: "Dominican Republic",
    image: "https://wallpapers.com/images/hd/north-america-punta-cana-xcmwb7gxu6seyzbr.jpg",
    tours: 12,
    lat: 18.5601,
    lng: -68.3725,
    description: "White sand beaches and turquoise waters. The Caribbean paradise.",
  },
  {
    id: 2,
    name: "Santo Domingo",
    country: "Dominican Republic",
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0f/04/56/f5.jpg",
    tours: 8,
    lat: 18.4861,
    lng: -69.9312,
    description: "The first city of the New World. History, culture and gastronomy.",
  },
  {
    id: 3,
    name: "Samaná",
    country: "Dominican Republic",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
    tours: 6,
    lat: 19.2061,
    lng: -69.3363,
    description: "Waterfalls, humpback whales and untouched nature.",
  },
];

export const testimonios = [
  {
    name: "Sarah Thompson",
    country: "New York, USA",
    avatar: "https://i.pravatar.cc/80?img=5",
    rating: 5,
    text: "The Saona Island tour was absolutely magical. The natural pool is incredible and the guides are very professional.",
    tour: "Saona Island",
  },
  {
    name: "Mike Johnson",
    country: "Miami, USA",
    avatar: "https://i.pravatar.cc/80?img=12",
    rating: 5,
    text: "Swimming with dolphins was the experience of a lifetime. My kids won't stop talking about it. 100% recommended!",
    tour: "Swimming with Dolphins",
  },
  {
    name: "Emily Davis",
    country: "Los Angeles, USA",
    avatar: "https://i.pravatar.cc/80?img=9",
    rating: 5,
    text: "The sunset catamaran with open bar was perfect for our honeymoon. Thank you Fantasy Travels.",
    tour: "Catamaran Sunset",
  },
];

export const blogPosts = [
  {
    id: 1,
    slug: "things-to-do-punta-cana-2026",
    title: "Things to Do in Punta Cana in 2026: Complete Guide",
    excerpt: "Discover the best activities, beaches and experiences you can't miss in Punta Cana this year.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    date: "2026-03-15",
    readTime: "8 min",
    category: "Guides",
  },
  {
    id: 2,
    slug: "saona-island-complete-guide",
    title: "Saona Island: Everything You Need to Know Before You Go",
    excerpt: "The most famous island in the Dominican Republic. How to get there, what to bring and the best tips to enjoy it.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    date: "2026-02-28",
    readTime: "6 min",
    category: "Destinations",
  },
  {
    id: 3,
    slug: "best-time-visit-caribbean",
    title: "Best Time to Visit the Caribbean in 2026",
    excerpt: "Seasons, weather, prices and tips to plan your perfect Caribbean trip.",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
    date: "2026-02-10",
    readTime: "5 min",
    category: "Tips",
  },
];
